language: node_js
node_js:
  - "5.1.0"
script: make
env:
  - CXX=g++-4.8
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - zlib1g-dev
      - libpng12-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8
